sudo: required
language: java
script: ant run

services:
  - docker

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker build -t dlablon/lonrep .;  
    docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD";
    docker push dlablon/lonrep;
    fi
