sudo: required
language: java
script: ant run

services: 
  - docker

branches:
   only:
      master
      
after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u "dlablon" -p "uasinDH1";
    docker build -t dlablon/lonrep;  
    docker push dlablon/lonrep;
    fi
